t3kit/t3kit-starter

README.md

Issue Number: no
add info about TYPO3 version supporting by t3kit

[DOC] update roadmap

---

.t3kit/community/ddev/README.md
.t3kit/community/ddev/setddevbasevariant.sh
.t3kit/community/ddev/setupddev.sh
composer.json
public/typo3conf/AdditionalConfiguration.php

Fix ddev implementation

---

.github/workflows/code-guidelines.yml
.github/workflows/git-commit.yml
.github/workflows/local-dev-evironment.yml

[TASK] update GitHub actions

---

.localconf/community/ddev/dot-ddev-directory/docker-compose.environment.yaml
public/typo3conf/AdditionalConfiguration.php

Introduces minor adjustments to DDEV configuration to keep up with recent changes to t3kit

[TASK] DDEV compatibility as of 10 October 2020

---

.localconf/community/ddev/README.md
.localconf/community/ddev/dot-ddev-directory/commands/web/typo3
.localconf/community/ddev/dot-ddev-directory/commands/web/typo3cms

- Updates the path to the database dump in the DDEV readme file.
- Removes the DDEV commands `typo3` and `typo3cms`, as DDEV now adds its own version of these commands automatically.

[TASK] Updated DDEV support

---

.github/workflows/code-guidelines.yml
.github/workflows/git-commit.yml
.github/workflows/local-dev-evironment.yml

[TEST] update github actions, predefine php version, add composer cache

---

.github/workflows/local-dev-evironment.yml
composer.json

[TEST] speed up GA tests, add npm-install-and-build step

---

.localconf/community/ddev/README.md
.localconf/community/ddev/dot-ddev-directory/web-build/Dockerfile

None.
* Upgrades NPM in the DDEV Docker image to support the t3kit NPM requirements.
* Updated DDEV documentation with NPM commands.

[BUGFIX] DDEV: Improvements to NPM support

---

.localconf/community/ddev/dot-ddev-directory/web-build/Dockerfile

In case something needs to be compiled with npm, installing the build-essential package with apt-get as a part of the Docker file will do the trick.
Adds to the DDEV web Dockerfile. In case something needs to be compiled with npm, installing the build-essential package with apt-get as a part of the Docker file will do the trick.

[TASK] DDEV: Add build-essential to web-build

---

.github/workflows/code-guidelines.yml
.github/workflows/local-dev-evironment.yml
.localconf/db/setupdb.sh
.localconf/local.env

- [] [FEATURE] - A new feature

[TEST] update GA tests, add Package artifact setup step

---

.localconf/community/ddev/setupddev.sh

* Installs GraphicsMagick for compatibility with t3kit's default GFX configuration
* Also disables settings management to avoid the error message about AdditionalConfiguration.php already having been written.

[BUGFIX] DDEV: Install GraphicsMagick

---

.localconf/community/ddev/dot-ddev-directory/web-build/Dockerfile

Upgrade NVM/NODE/NPM versions in Dockerfile

[TASK] DDEV: update NVM/NODE/NPM versions

---

.localconf/community/ddev/setupddev.sh

Adds g++ and build-essential packages to extra web environment packages. Otherwise NPM compile might fail.

[BUGFIX] DDEV: Include g++ and build-essential in extra packages

---

.github/workflows/local-dev-evironment.yml

[BUGFIX] fix local development env github action test

---

.localconf/local.env

Fixes a typo in comment for local.env

[BUGFIX] Fix typo in comment for local.env

---

.localconf/platformsh/.platform.app.example.yaml

Run TYPO3 upgrade wizards on deploy. This makes deployment more seamless becuase you can automate changes in the content realm.

[FEATURE] Platform.sh: Run upgrade wizards on deploy

---

.phpcs.xml

[BUGFIX] Exclude typo3conf/autoload

---

public/typo3conf/ext/theme_newcustomproject/theme/src/css/main/global/helpers/buttons.css
public/typo3conf/ext/theme_newcustomproject/theme/src/css/main/global/nav/side-navigation.css
public/typo3conf/ext/theme_newcustomproject/theme/src/css/main/global/root.css

Issue Number: #76 
Remove commas in HSL properties for CSS and streamline usage of percentage in them also.

[BUGFIX] Remove commas in HSL properties for CSS

---

.localconf/community/ddev/README.md

[DOC] DDEV: Instructions for watching changes with NPM

---

.localconf/platformsh/.platform.app.example.yaml
composer.json
composer.lock

* Adds a dependency to helhum/typo3-console.
* Adds destructive database schema updates to Platform.sh's deploy hook.
* Updates all composer dependencies.

[FEATURE] TYPO3 Console dep + destructive DB update on Platform.sh

---

public/typo3conf/LocalConfiguration.php

[BUGFIX] Use utf8mb4 in database 

---

.localconf/platformsh/scripts/db/syncdb.sh

Add missing typo3-console scripts for syncdb command. Big thanks goes to @pixelmatseriks and @mesosa !

[BUGFIX] Add missing typo3-console scripts for syncdb command

---

.localconf/platformsh/.platform/routes.yaml

Add strict_transport_security for headers in Platform.sh.

[TASK] Add strict_transport_security for headers in Platform.sh

---

public/typo3conf/LocalConfiguration.php

This is to prevent that when creating a new page and enabling it , not to be logged out from the TYPO3 backend.
This is to prevent that when creating a new page and enabling it , not to be logged out from the TYPO3 backend.

[BUGFIX] Disable Feature Toggle ''disable-subrequestPageErrors''
